name              'yum-elrepo'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures the elrepo yum repository'
version           '2.2.1'
source_url        'https://github.com/sous-chefs/yum-elrepo'
issues_url        'https://github.com/sous-chefs/yum-elrepo/issues'
chef_version      '>= 12.15'

supports 'amazon'
supports 'centos'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
